#!/bin/bash
# Launches an instance of polybar

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar on HDMI-A-3(main), using default config location ~/.config/polybar/config
polybar bar &

second_monitor=$(xrandr --query | grep 'DVI-D-0')
if [[ $second_monitor = *connected* ]]; then
	polybar second_bar &
fi
echo "Polybar(s) launched..."
